name: "\U0001F41E Bug report"
description: Create a report to help us improve Pinia ORM
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please use a template below to create a minimal reproduction
        👉 https://pinia-orm-play.codedredd.de/ (pinia-orm playground, pick this if you are not using nuxt) 
        👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitzk (basic nuxt on stackblitz)
        👉 https://codesandbox.io/s/github/nuxt/starter/tree/v3-codesandbox (basic nuxt on codesandbox)
  - type: textarea
    id: bug-env
    attributes:
      label: Environment
      description: Put *playground* when in the playground. Otherwise you could use `npx nuxi info` for nuxt to fill this section.
      placeholder: Environment
    validations:
      required: false 
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo that can reproduce the problem you ran into. A [**minimal reproduction**](https://v3.nuxtjs.org/community/reporting-bugs#create-a-minimal-reproduction) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided we might close it.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: additonal
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here`
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
      render: shell
