on:
  push:
    branches:
      - '**'
    paths:
      - docs/**

name: Update algolia indexes for docs

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Run algolia crawler
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: 'CUDIBUZGZJ'
          algolia_api_key: ${{ secrets.ALGOLIA_API}}
          file: 'docs/algolia.config.json'
